from flask import Flask, render_template, request
from dotenv import load_dotenv
import requests
import os
import time

load_dotenv()

app = Flask(__name__)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
MODEL = "gemini-3.6-flash"


def demo_analysis(issue):
    return f"""DEMO FALLBACK — Gemini API temporarily unavailable

1. Short Summary
The reported issue is:

{issue}

2. Issue Category
Operational Issue

3. Urgency
Medium

4. Possible Cause
The exact cause cannot be determined from the information provided.

5. Recommended Next Step
Collect relevant timestamps, system records, and information from the teams involved to identify where the operational delay or failure is occurring.

Note:
This is a fallback demonstration response. In normal operation, the analysis is generated by the Gemini API.
"""


@app.route("/", methods=["GET", "POST"])
def home():
    result = None
    error = None

    if request.method == "POST":
        issue = request.form["issue"]

        prompt = f"""
You are an operations analyst.

Analyze this operational issue:

{issue}

Give me:
1. A short summary
2. Issue category
3. Urgency: Low, Medium, or High
4. Possible cause
5. Recommended next step

Only use information supported by the issue.
Clearly say when something is uncertain.
"""

        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{MODEL}:generateContent?key={GEMINI_API_KEY}"
        )

        response = None

        for attempt in range(3):
            try:
                response = requests.post(
                    url,
                    json={
                        "contents": [
                            {
                                "parts": [
                                    {"text": prompt}
                                ]
                            }
                        ]
                    },
                    timeout=30
                )

                if response.status_code != 503:
                    break

                time.sleep(2)

            except requests.RequestException as e:
                error = f"Request error: {e}"
                break

        if response and response.ok:
            data = response.json()
            result = data["candidates"][0]["content"]["parts"][0]["text"]

        elif response and response.status_code in [429, 503]:
            result = demo_analysis(issue)

        elif not error:
            error = f"API error {response.status_code}: {response.text}"

    return render_template(
        "index.html",
        result=result,
        error=error
    )


if __name__ == "__main__":
    app.run(debug=True)